#!/usr/bin/env python3
"""Generate this tool's per-language pages: ru/, fr/, de/, es/, it/, ja/, zh/.

Search engines only see the HTML they're served, so a UI translated by JS
after load is invisible to them. Each language gets its own URL instead:
/<tool>/<lang>/index.html is a copy of index.html with

  - <html lang> + data-url-lang (the i18n code pins the UI language to it)
  - a translated <title>, meta description and og/twitter title + description
  - its own canonical / og:url / og:locale and the JSON-LD "url"
  - relative asset paths prefixed with ../ (no <base>: it would break
    fragment references like url(#…) SVG filters)

It also keeps the hreflang block in index.html in sync, rewrites sitemap.xml
with every language URL + xhtml:link alternates, and does the same for this
tool's entries in the hub's ../cyberdeck-tools/sitemap.xml (when present).

index.html (English) is the only source: NEVER edit the generated folders.
bump_version.py runs this script after every bump; run it by hand after any
other index.html change:

    python make_langs.py
"""
import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
TOOL = "sinforge-ui"
BASE = f"https://cyberdeck.tools/{TOOL}/"
INDEX = ROOT / "index.html"
SITEMAP = ROOT / "sitemap.xml"
HUB_SITEMAP = ROOT.parent / "cyberdeck-tools" / "sitemap.xml"

LANGS = ["en", "ru", "fr", "de", "es", "it", "ja", "zh"]
LOCALES = {"en": "en_US", "ru": "ru_RU", "fr": "fr_FR", "de": "de_DE",
           "es": "es_ES", "it": "it_IT", "ja": "ja_JP", "zh": "zh_CN"}

# Search-result copy per language (English lives in index.html itself).
# title <= ~60 chars, desc <= ~160 (Google cuts longer ones); og_* feed both
# the Open Graph and the Twitter card tags.
SEO = {
    "ru": dict(
        title='SINFORGE — генератор киберпанк-удостоверений и бейджей',
        desc='Бесплатный генератор киберпанк-документов: удостоверения, SIN, бейджи и ключ-карты для реквизита НРИ и LARP. Экспорт PNG, без загрузки на сервер.',
        og_title='SINFORGE — генератор киберпанк-удостоверений',
        og_desc='Создавайте киберпанк-удостоверения, SIN, бейджи и ключ-карты прямо в браузере для НРИ и LARP. Экспорт PNG, ничего не загружается.',
    ),
    "fr": dict(
        title="SINFORGE — Générateur de cartes d'identité cyberpunk",
        desc="Générateur gratuit de documents cyberpunk : cartes d'identité, SIN, badges et cartes d'accès pour vos accessoires de JDR et de GN. Export PNG, aucun envoi.",
        og_title="SINFORGE — Cartes d'identité et badges cyberpunk",
        og_desc="Forgez cartes d'identité, SIN, badges et cartes d'accès cyberpunk dans votre navigateur pour le JDR et le GN. Export PNG, rien n'est envoyé.",
    ),
    "de": dict(
        title='SINFORGE — Cyberpunk-Ausweis-, Badge- und Keycard-Generator',
        desc='Kostenloser Cyberpunk-Dokumentgenerator: Ausweise, SINs, Event-Badges und Keycards als Requisiten für Pen & Paper und LARP. PNG-Export, kein Upload.',
        og_title='SINFORGE — Cyberpunk-Ausweis- & Badge-Generator',
        og_desc='Erstelle Cyberpunk-Ausweise, SINs, Badges und Keycards im Browser für Pen & Paper und LARP. PNG-Export, nichts wird hochgeladen.',
    ),
    "es": dict(
        title='SINFORGE — Generador de carnés de identidad cyberpunk',
        desc='Generador gratuito de documentos cyberpunk: carnés de identidad, SIN, acreditaciones y tarjetas de acceso para atrezo de rol y LARP. Exportación PNG, sin subidas.',
        og_title='SINFORGE — Carnés y acreditaciones cyberpunk',
        og_desc='Crea carnés de identidad, SIN, acreditaciones y tarjetas de acceso cyberpunk en tu navegador para rol y LARP. Exportación PNG, nada se sube.',
    ),
    "it": dict(
        title="SINFORGE — Generatore di carte d'identità cyberpunk",
        desc="Generatore gratuito di documenti cyberpunk: carte d'identità, SIN, pass e keycard per oggetti di scena di GDR e LARP. Esportazione PNG, nessun caricamento.",
        og_title="SINFORGE — Carte d'identità e pass cyberpunk",
        og_desc="Crea carte d'identità, SIN, pass e keycard cyberpunk nel browser per GDR e LARP. Esportazione PNG, nulla viene caricato.",
    ),
    "ja": dict(
        title='SINFORGE — サイバーパンク風IDカード・バッジメーカー',
        desc='サイバーパンク風の書類を無料で作成。IDカード、SIN、イベントバッジ、キーカードを TRPG や LARP の小道具として作り、PNG で書き出せます。アップロード不要。',
        og_title='SINFORGE — サイバーパンク風IDカードメーカー',
        og_desc='ブラウザでサイバーパンク風の IDカード、SIN、バッジ、キーカードを作成。TRPG や LARP の小道具に。PNG 書き出し、アップロード不要。',
    ),
    "zh": dict(
        title='SINFORGE — 赛博朋克身份证与胸牌生成器',
        desc='免费的赛博朋克证件生成器：制作身份证、SIN、活动胸牌和门禁卡，用作跑团与 LARP 道具，导出 PNG，图片不会上传。',
        og_title='SINFORGE — 赛博朋克身份证生成器',
        og_desc='在浏览器中制作赛博朋克风格的身份证、SIN、胸牌和门禁卡，适合跑团与 LARP，导出 PNG。',
    ),
}

HREFLANG_START = "<!-- hreflang: generated by make_langs.py -->"
HREFLANG_END = "<!-- /hreflang -->"
GENERATED = "<!-- GENERATED by make_langs.py from ../index.html — edit index.html, then re-run -->"


def url(lang):
    return BASE if lang == "en" else f"{BASE}{lang}/"


def esc(s):
    return html.escape(s, quote=True)


def sub1(text, pattern, repl, what):
    text, n = re.subn(pattern, repl, text, count=1)
    if n != 1:
        sys.exit(f"error: {what} not found in index.html")
    return text


def set_meta(text, attr, name, value):
    return sub1(text, rf'(<meta {attr}="{re.escape(name)}" content=")[^"]*(" />)',
                lambda m: m.group(1) + esc(value) + m.group(2), f"{attr}={name}")


def hreflang_block():
    links = [f'<link rel="alternate" hreflang="{l}" href="{url(l)}" />' for l in LANGS]
    links.append(f'<link rel="alternate" hreflang="x-default" href="{BASE}" />')
    return "\n".join([HREFLANG_START, *links, HREFLANG_END])


def with_hreflang(text):
    block = hreflang_block()
    if HREFLANG_START in text:
        return re.sub(re.escape(HREFLANG_START) + r".*?" + re.escape(HREFLANG_END), lambda m: block, text, flags=re.S)
    return sub1(text, r'(<link rel="canonical" href="[^"]*" />\n)', lambda m: m.group(1) + block + "\n", "canonical")


def prefix_paths(text):
    """../ before relative src / href attributes. Inside a <script> block only
    the opening tag is touched (its src=), so template strings in the inline
    JS are left alone."""
    rel = re.compile(r'(\s(?:src|href)=")(?!https?:|data:|#|/|mailto:|javascript:|\.\./)([^"]+")')

    def fix(part):
        if not part.startswith("<script"):
            return rel.sub(r"\1../\2", part)
        tag_end = part.index(">") + 1
        return rel.sub(r"\1../\2", part[:tag_end]) + part[tag_end:]

    return "".join(fix(p) for p in re.split(r"(<script\b.*?</script>)", text, flags=re.S))


def localize(src, lang):
    t, s = SEO[lang], src
    s = sub1(s, r"\n", "\n" + GENERATED + "\n", "first line")  # right after the version comment
    s = sub1(s, r'<html lang="en">', f'<html lang="{lang}" data-url-lang="{lang}">', '<html lang="en">')
    s = sub1(s, r"<title>[^<]*</title>", lambda m: f"<title>{esc(t['title'])}</title>", "<title>")
    s = set_meta(s, "name", "description", t["desc"])
    s = set_meta(s, "property", "og:title", t["og_title"])
    s = set_meta(s, "property", "og:description", t["og_desc"])
    s = set_meta(s, "name", "twitter:title", t["og_title"])
    s = set_meta(s, "name", "twitter:description", t["og_desc"])
    s = set_meta(s, "property", "og:url", url(lang))
    s = sub1(s, r'(<link rel="canonical" href=")[^"]*(" />)', lambda m: m.group(1) + url(lang) + m.group(2), "canonical")
    locales = [f'<meta property="og:locale" content="{LOCALES[lang]}" />'] + [
        f'<meta property="og:locale:alternate" content="{LOCALES[l]}" />' for l in LANGS if l != lang]
    block = re.compile(r'<meta property="og:locale" content="[^"]*" />\n(?:<meta property="og:locale:alternate" content="[^"]*" />\n)*')
    if block.search(s):
        s = block.sub(lambda m: "\n".join(locales) + "\n", s, count=1)
    else:  # no og:locale block in index.html: add one after og:url
        s = sub1(s, r'(<meta property="og:url" content="[^"]*" />\n)', lambda m: m.group(1) + "\n".join(locales) + "\n", "og:url")
    s = sub1(s, rf'("url": "){re.escape(BASE)}(")', lambda m: m.group(1) + url(lang) + m.group(2), 'JSON-LD "url"')
    return prefix_paths(s)


def url_entries(lastmod, priority_en, priority_lang, indent="  "):
    alts = "".join(f'\n{indent}  <xhtml:link rel="alternate" hreflang="{l}" href="{url(l)}" />' for l in LANGS)
    alts += f'\n{indent}  <xhtml:link rel="alternate" hreflang="x-default" href="{BASE}" />'
    out = []
    for l in LANGS:
        out.append(f"{indent}<url>\n{indent}  <loc>{url(l)}</loc>\n{indent}  <lastmod>{lastmod}</lastmod>\n"
                   f"{indent}  <changefreq>weekly</changefreq>\n{indent}  <priority>{priority_en if l == 'en' else priority_lang}</priority>"
                   f"{alts}\n{indent}</url>\n")
    return "".join(out)


URLSET_OPEN = '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">'


def write_tool_sitemap(lastmod):
    SITEMAP.write_text('<?xml version="1.0" encoding="UTF-8"?>\n' + URLSET_OPEN + "\n"
                       + url_entries(lastmod, "1.0", "0.9") + "</urlset>\n", encoding="utf-8")


def update_hub_sitemap(lastmod):
    if not HUB_SITEMAP.exists():
        print(f"note: {HUB_SITEMAP} not found, hub sitemap skipped")
        return
    text = HUB_SITEMAP.read_text(encoding="utf-8")
    blocks = list(re.finditer(r"  <url>\n.*?\n  </url>\n", text, flags=re.S))
    mine = [b for b in blocks if re.search(rf"<loc>{re.escape(BASE)}", b.group(0))]
    if not mine:
        print(f"note: {BASE} is not listed in the hub sitemap, skipped")
        return
    prio = re.search(r"<priority>([^<]+)</priority>", mine[0].group(0))
    p_en = prio.group(1) if prio else "0.8"
    p_lang = f"{max(0.1, float(p_en) - 0.1):.1f}"
    new = url_entries(lastmod, p_en, p_lang)
    out, pos = [], 0
    for i, b in enumerate(mine):
        out.append(text[pos:b.start()])
        if i == 0:
            out.append(new)
        pos = b.end()
    out.append(text[pos:])
    text = "".join(out)
    text = re.sub(r"<urlset[^>]*>", URLSET_OPEN, text, count=1)
    HUB_SITEMAP.write_text(text, encoding="utf-8")
    print("sitemap: cyberdeck-tools/sitemap.xml updated (commit the hub repo too)")


def main():
    for lang, t in SEO.items():
        for k, limit in (("title", 60), ("desc", 165)):
            if len(t[k]) > limit:
                print(f"warning: {lang} {k} is {len(t[k])} chars (> {limit})")

    src = with_hreflang(INDEX.read_text(encoding="utf-8"))
    INDEX.write_text(src, encoding="utf-8")
    for lang in LANGS[1:]:
        out = ROOT / lang / "index.html"
        out.parent.mkdir(exist_ok=True)
        out.write_text(localize(src, lang), encoding="utf-8")
    m = re.search(r'"dateModified": "([^"]+)"', src)
    lastmod = m.group(1) if m else __import__("datetime").date.today().isoformat()
    write_tool_sitemap(lastmod)
    update_hub_sitemap(lastmod)
    print(f"langs: wrote {', '.join(l + '/' for l in LANGS[1:])} (lastmod {lastmod})")


if __name__ == "__main__":
    main()
